BIBTEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\bibtex.exe']
BINDIR = 'C:\\Users\\MICHAE~1\\AppData\\Local\\Temp/bin'
DVIPS = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\dvips.exe']
DVIPSFLAGS = '-Ppdf'
LATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\latex.exe']
LIBDIR = 'C:\\Users\\MICHAE~1\\AppData\\Local\\Temp/lib'
MAKEGLOSSARIES = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\makeglossaries.exe']
MAKEINDEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\makeindex.exe']
MATLABCMD = ['C:\\Program Files\\MATLAB\\R2015b\\bin\\matlab.exe']
MATLABFLAGS = '-wait -nodesktop -nosplash -minimize'
PDF2PS = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\pdf2ps.exe']
PDFLATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\pdflatex.exe']
PDFLATEXFLAGS = '-shell-escape'
PREFIX = 'C:\\Users\\MICHAE~1\\AppData\\Local\\Temp'
PS2PDF = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\ps2pdf.exe']
PYTHONPATH = 'C:\\WAF\\V7'
TEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\tex.exe']
XELATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\xelatex.exe']
